"""SuperQode harness primitives."""

from .events import HarnessEvent
from .loader import (
    harness_spec_from_dict,
    harness_spec_json_schema,
    harness_spec_to_dict,
    load_harness_spec,
    resolve_harness_inheritance,
    save_harness_spec,
)
from .model_policy import EffectiveModelPolicy, resolve_harness_model_policy
from .output import (
    RESULT_END,
    RESULT_START,
    TypedOutputError,
    build_typed_output_prompt,
    parse_typed_output,
)
from .store import (
    FileHarnessStore,
    HarnessEventGraph,
    HarnessGraphEdge,
    HarnessGraphNode,
    HarnessInputRecord,
    HarnessRunRecord,
    HarnessSessionRecord,
    MemoryHarnessStore,
    SQLiteHarnessStore,
    create_harness_store,
    generate_input_id,
    generate_run_id,
)
from .spec import (
    AgentSpec,
    ContextSpec,
    ExecutionPolicySpec,
    HarnessFlavor,
    HarnessSpec,
    HookRuleSpec,
    HooksSpec,
    ModelPolicySpec,
    ObservabilitySpec,
    PermissionRuleSpec,
    RuntimeSpec,
    ChecksSpec,
    CheckStepSpec,
    WorkflowMode,
    WorkflowSpec,
)
from .templates import BUILTIN_TEMPLATES, get_harness_template

_LAZY_IMPORTS = {
    # Hooks
    "build_hook_registry": (".hooks", "build_hook_registry"),
    "register_spec_hooks": (".hooks", "register_spec_hooks"),
    "register_store_forwarders": (".hooks", "register_store_forwarders"),
    "resolve_hook_handler": (".hooks", "resolve_hook_handler"),
    # Rule-based permissions
    "build_permission_handler": (".permissions", "build_permission_handler"),
    "evaluate_permission_rules": (".permissions", "evaluate_permission_rules"),
    "rule_matches": (".permissions", "rule_matches"),
    # Persistent approval memory
    "approval_memory_path": (".approval_memory", "approval_memory_path"),
    "load_approval_memory_rules": (".approval_memory", "load_approval_memory_rules"),
    "remember_approval_decision": (".approval_memory", "remember_approval_decision"),
    # Compiler
    "compile_to_headless_profile": (".compiler", "compile_to_headless_profile"),
    "spec_from_headless_profile": (".compiler", "spec_from_headless_profile"),
    # Plain-English explanation
    "HarnessExplanation": (".explain", "HarnessExplanation"),
    "explain_harness": (".explain", "explain_harness"),
    "render_explanation": (".explain", "render_explanation"),
    # Interactive wizard
    "WizardAnswers": (".wizard", "WizardAnswers"),
    "build_wizard_spec": (".wizard", "build_wizard_spec"),
    "WIZARD_STARTERS": (".wizard", "WIZARD_STARTERS"),
    "APPROVAL_PROFILES": (".wizard", "APPROVAL_PROFILES"),
    "TOOL_CALL_FORMATS": (".wizard", "TOOL_CALL_FORMATS"),
    # Omnigent compatibility
    "import_omnigent_agent": (".omnigent_importer", "import_omnigent_agent"),
    "load_omnigent_agent": (".omnigent_importer", "load_omnigent_agent"),
    "omnigent_agent_to_harness_spec": (
        ".omnigent_importer",
        "omnigent_agent_to_harness_spec",
    ),
    # Runtime backends
    "ADKHarnessBackend": (".backends", "ADKHarnessBackend"),
    "ClaudeAgentSDKHarnessBackend": (".backends", "ClaudeAgentSDKHarnessBackend"),
    "CodexSDKHarnessBackend": (".backends", "CodexSDKHarnessBackend"),
    "HarnessBackend": (".backends", "HarnessBackend"),
    "HarnessBackendCapabilities": (".backends", "HarnessBackendCapabilities"),
    "HarnessBackendInspection": (".backends", "HarnessBackendInspection"),
    "HarnessBackendIssue": (".backends", "HarnessBackendIssue"),
    "HarnessBackendRequest": (".backends", "HarnessBackendRequest"),
    "HarnessBackendResult": (".backends", "HarnessBackendResult"),
    "DeepAgentsHarnessBackend": (".backends", "DeepAgentsHarnessBackend"),
    "OpenAIAgentsHarnessBackend": (".backends", "OpenAIAgentsHarnessBackend"),
    "PydanticAIHarnessBackend": (".backends", "PydanticAIHarnessBackend"),
    "RuntimeHarnessBackend": (".backends", "RuntimeHarnessBackend"),
    "backend_capabilities": (".backends", "backend_capabilities"),
    "create_harness_backend": (".backends", "create_harness_backend"),
    "inspect_harness_backend": (".backends", "inspect_harness_backend"),
    "known_harness_backend_names": (".backends", "known_harness_backend_names"),
    # Kernel
    "HarnessKernel": (".kernel", "HarnessKernel"),
    "HarnessRunRequest": (".kernel", "HarnessRunRequest"),
    "HarnessRunResult": (".kernel", "HarnessRunResult"),
    "HarnessSession": (".kernel", "HarnessSession"),
    "init_harness": (".kernel", "init_harness"),
    # Sandbox
    "SandboxCapabilities": (".sandbox", "SandboxCapabilities"),
    "SandboxCapabilityBackend": (".sandbox", "SandboxCapabilityBackend"),
    "HarnessSandboxBackend": (".sandbox", "HarnessSandboxBackend"),
    "LocalSandboxBackend": (".sandbox", "LocalSandboxBackend"),
    "SandboxBackend": (".sandbox", "SandboxBackend"),
    "SandboxFileInfo": (".sandbox", "SandboxFileInfo"),
    "SandboxPolicy": (".sandbox", "SandboxPolicy"),
    "SandboxShellResult": (".sandbox", "SandboxShellResult"),
    "apply_backend_permissions": (".sandbox", "apply_backend_permissions"),
    "build_openai_sandbox_agent": (".sandbox", "build_openai_sandbox_agent"),
    "build_openai_sandbox_client": (".sandbox", "build_openai_sandbox_client"),
    "build_openai_sandbox_manifest": (".sandbox", "build_openai_sandbox_manifest"),
    "build_openai_sandbox_run_config": (".sandbox", "build_openai_sandbox_run_config"),
    "get_sandbox_capabilities": (".sandbox", "get_sandbox_capabilities"),
    "is_openai_sandbox_backend_available": (".sandbox", "is_openai_sandbox_backend_available"),
    "require_shell": (".sandbox", "require_shell"),
    "require_write": (".sandbox", "require_write"),
    "sandbox_policy_from_execution_policy": (".sandbox", "sandbox_policy_from_execution_policy"),
    "supported_openai_sandbox_backends": (".sandbox", "supported_openai_sandbox_backends"),
    # Workflow
    "WorkflowResult": (".workflow", "WorkflowResult"),
    "WorkflowProgress": (".workflow", "WorkflowProgress"),
    "WorkflowStep": (".workflow", "WorkflowStep"),
    "run_workflow": (".workflow", "run_workflow"),
    "workflow_steps_from_spec": (".workflow", "workflow_steps_from_spec"),
    "WorkflowPreset": (".workflow_presets", "WorkflowPreset"),
    "WORKFLOW_PRESETS": (".workflow_presets", "WORKFLOW_PRESETS"),
    "apply_workflow_preset": (".workflow_presets", "apply_workflow_preset"),
    "get_workflow_preset": (".workflow_presets", "get_workflow_preset"),
    "list_workflow_presets": (".workflow_presets", "list_workflow_presets"),
    # Performance
    "Accelerator": (".accelerator", "Accelerator"),
    "AcceleratorConfig": (".accelerator", "AcceleratorConfig"),
    "get_accelerator": (".accelerator", "get_accelerator"),
    "prewarm": (".accelerator", "prewarm"),
    "cached_system_prompt": (".accelerator", "cached_system_prompt"),
    # Diagnostics
    "HarnessCheck": (".diagnostics", "HarnessCheck"),
    "HarnessDoctorReport": (".diagnostics", "HarnessDoctorReport"),
    "build_harness_evidence": (".diagnostics", "build_harness_evidence"),
    "build_harness_replay_plan": (".diagnostics", "build_harness_replay_plan"),
    "doctor_harness": (".diagnostics", "doctor_harness"),
    "fork_harness_run": (".diagnostics", "fork_harness_run"),
    "inspect_harness": (".diagnostics", "inspect_harness"),
    "plan_harness_graph": (".diagnostics", "plan_harness_graph"),
    "render_harness_doctor": (".diagnostics", "render_harness_doctor"),
    "render_harness_evidence": (".diagnostics", "render_harness_evidence"),
    "render_harness_graph": (".diagnostics", "render_harness_graph"),
    "render_harness_inspect": (".diagnostics", "render_harness_inspect"),
    "render_harness_replay_plan": (".diagnostics", "render_harness_replay_plan"),
    # Test/eval/registry
    "run_harness_smoke_test": (".testing", "run_harness_smoke_test"),
    "render_harness_smoke_test": (".testing", "render_harness_smoke_test"),
    "build_failure_digest": (".testing", "build_failure_digest"),
    "HARNESS_DIMENSIONS": (".testing", "HARNESS_DIMENSIONS"),
    "dimension_for_category": (".testing", "dimension_for_category"),
    "load_eval_tasks": (".eval", "load_eval_tasks"),
    "run_harness_eval": (".eval", "run_harness_eval"),
    "harness_eval_regressions": (".eval", "harness_eval_regressions"),
    "render_harness_eval": (".eval", "render_harness_eval"),
    "publish_harness_spec": (".registry", "publish_harness_spec"),
    "list_registry_specs": (".registry", "list_registry_specs"),
    "install_registry_spec": (".registry", "install_registry_spec"),
    "export_metaharness_project": (".optimize", "export_metaharness_project"),
    "run_metaharness_project": (".optimize", "run_metaharness_project"),
    "summarize_metaharness_run": (".optimize", "summarize_metaharness_run"),
    "metaharness_candidate_ledger": (".optimize", "metaharness_candidate_ledger"),
    "apply_metaharness_best_spec": (".optimize", "apply_metaharness_best_spec"),
    "render_optimize_payload": (".optimize", "render_optimize_payload"),
    "render_metaharness_summary": (".optimize", "render_metaharness_summary"),
    "render_metaharness_ledger": (".optimize", "render_metaharness_ledger"),
}


def __getattr__(name: str):
    if name not in _LAZY_IMPORTS:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    import importlib

    module_name, attr_name = _LAZY_IMPORTS[name]
    value = getattr(importlib.import_module(module_name, __name__), attr_name)
    globals()[name] = value
    return value


__all__ = [
    # Agent harness specs
    "AgentSpec",
    "ChecksSpec",
    "CheckStepSpec",
    "ContextSpec",
    "ExecutionPolicySpec",
    "HarnessFlavor",
    "HarnessSpec",
    "HookRuleSpec",
    "HooksSpec",
    "ModelPolicySpec",
    "PermissionRuleSpec",
    "ObservabilitySpec",
    "RuntimeSpec",
    "WorkflowMode",
    "WorkflowProgress",
    "WorkflowPreset",
    "WorkflowResult",
    "WorkflowSpec",
    "WorkflowStep",
    "WORKFLOW_PRESETS",
    "BUILTIN_TEMPLATES",
    "EffectiveModelPolicy",
    "RESULT_END",
    "RESULT_START",
    "ADKHarnessBackend",
    "ClaudeAgentSDKHarnessBackend",
    "CodexSDKHarnessBackend",
    "HarnessBackend",
    "HarnessBackendCapabilities",
    "HarnessBackendInspection",
    "HarnessBackendIssue",
    "HarnessBackendRequest",
    "HarnessBackendResult",
    "HarnessEvent",
    "HarnessKernel",
    "HarnessCheck",
    "HarnessDoctorReport",
    "HarnessEventGraph",
    "HarnessGraphEdge",
    "HarnessGraphNode",
    "HarnessInputRecord",
    "HarnessRunRequest",
    "HarnessRunResult",
    "HarnessSession",
    "HarnessRunRecord",
    "HarnessSessionRecord",
    "FileHarnessStore",
    "MemoryHarnessStore",
    "SQLiteHarnessStore",
    "DeepAgentsHarnessBackend",
    "OpenAIAgentsHarnessBackend",
    "PydanticAIHarnessBackend",
    "RuntimeHarnessBackend",
    "HarnessSandboxBackend",
    "LocalSandboxBackend",
    "SandboxBackend",
    "SandboxCapabilities",
    "SandboxCapabilityBackend",
    "SandboxFileInfo",
    "SandboxPolicy",
    "SandboxShellResult",
    "TypedOutputError",
    "apply_backend_permissions",
    "apply_workflow_preset",
    "backend_capabilities",
    "build_hook_registry",
    "register_spec_hooks",
    "register_store_forwarders",
    "resolve_hook_handler",
    "build_permission_handler",
    "evaluate_permission_rules",
    "rule_matches",
    "approval_memory_path",
    "load_approval_memory_rules",
    "remember_approval_decision",
    "build_openai_sandbox_agent",
    "build_openai_sandbox_client",
    "build_openai_sandbox_manifest",
    "build_openai_sandbox_run_config",
    "build_typed_output_prompt",
    "build_harness_evidence",
    "build_harness_replay_plan",
    "compile_to_headless_profile",
    "HarnessExplanation",
    "explain_harness",
    "render_explanation",
    "WizardAnswers",
    "build_wizard_spec",
    "WIZARD_STARTERS",
    "APPROVAL_PROFILES",
    "TOOL_CALL_FORMATS",
    "create_harness_store",
    "generate_input_id",
    "fork_harness_run",
    "create_harness_backend",
    "doctor_harness",
    "get_harness_template",
    "get_workflow_preset",
    "get_sandbox_capabilities",
    "generate_run_id",
    "harness_spec_from_dict",
    "harness_spec_json_schema",
    "harness_spec_to_dict",
    "import_omnigent_agent",
    "inspect_harness",
    "init_harness",
    "inspect_harness_backend",
    "is_openai_sandbox_backend_available",
    "known_harness_backend_names",
    "list_workflow_presets",
    "load_omnigent_agent",
    "parse_typed_output",
    "plan_harness_graph",
    "require_shell",
    "require_write",
    "sandbox_policy_from_execution_policy",
    "supported_openai_sandbox_backends",
    "load_harness_spec",
    "save_harness_spec",
    "run_workflow",
    "workflow_steps_from_spec",
    "resolve_harness_model_policy",
    "resolve_harness_inheritance",
    "render_harness_doctor",
    "render_harness_evidence",
    "render_harness_graph",
    "render_harness_inspect",
    "render_harness_replay_plan",
    "run_harness_smoke_test",
    "render_harness_smoke_test",
    "build_failure_digest",
    "HARNESS_DIMENSIONS",
    "dimension_for_category",
    "harness_eval_regressions",
    "load_eval_tasks",
    "run_harness_eval",
    "render_harness_eval",
    "publish_harness_spec",
    "list_registry_specs",
    "install_registry_spec",
    "export_metaharness_project",
    "run_metaharness_project",
    "summarize_metaharness_run",
    "metaharness_candidate_ledger",
    "apply_metaharness_best_spec",
    "render_optimize_payload",
    "render_metaharness_summary",
    "render_metaharness_ledger",
    "omnigent_agent_to_harness_spec",
    "spec_from_headless_profile",
    # Performance
    "Accelerator",
    "AcceleratorConfig",
    "get_accelerator",
    "prewarm",
    "cached_system_prompt",
]
