"""Contract guard for the app_main / main refactor.

This test locks the public + private surface that the refactor MUST preserve.
It fails loudly if a method disappears from ``SuperQodeApp`` (e.g. accidentally
dropped while moving it into a mixin) or if a module-level symbol stops being
importable from ``superqode.app_main``.

The baseline inventory below was captured from ``main`` before the refactor
began (747 members beyond Textual's ``App``). Do NOT trim it to make the test
pass -- a missing name means behavior was lost.
"""

import pytest


def test_app_main_module_symbols_importable():
    # Symbols that other modules and tests import by name from superqode.app_main.
    from superqode.app_main import (  # noqa: F401
        SuperQodeApp,
        SelectionAwareInput,
        render_welcome,
        _harness_display_name,
        run_textual_app,
        get_session,
        get_mode,
        set_mode,
    )
    from superqode.app import run_textual_app as _rt  # launch path used by main.py  # noqa: F401


BASELINE_METHODS = (
    '_a2a_cmd', '_accept_prompt_completion', '_acp_cmd', '_acp_doctor_cmd',
    '_active_agent_loop', '_active_harness_spec', '_active_local_provider_model', '_add_mcp_server_config',
    '_adjust_scroll_for_item', '_agent_session_label', '_agents_cmd', '_all_local_skill_names',
    '_all_provider_ids', '_all_skill_completion_candidates', '_announce_pending_approvals', '_announce_self_contained_connection',
    '_answer_model_query', '_antigravity_cmd', '_antigravity_command_line', '_antigravity_version',
    '_apply_and_persist_theme', '_apply_codex_model_override', '_apply_interaction_mode', '_apply_live_models',
    '_apply_selection_buffer', '_apply_thinking_state', '_approval_cmd', '_approve_diff_entry',
    '_ask_agent_question', '_attach_cmd', '_auto_select_claude_model', '_auto_select_codex_model',
    '_auto_select_gemini_model', '_auto_select_opencode_model', '_auto_select_openhands_model', '_benchmark_cmd',
    '_build_cmd', '_build_palette_commands', '_byok_provider_completion_candidates', '_byok_provider_ids',
    '_call_ui', '_calm_tool_done', '_calm_tool_running', '_calm_verb_target',
    '_candidate_after_prefix', '_chat_cmd', '_chat_worker', '_check_provider_health',
    '_check_update_worker', '_claude_cmd', '_claude_commands_cmd', '_claude_model_cmd',
    '_claude_permission_cmd', '_claude_runtime_action', '_claude_runtime_or_connect', '_claude_sessions_cmd',
    '_claude_status', '_cleanup_on_exit', '_cleanup_terminals', '_clear_for_workspace',
    '_clear_message_queue', '_codex_account_cmd', '_codex_archive_cmd', '_codex_cmd',
    '_codex_config_error_hint', '_codex_config_error_hint_text', '_codex_effort_cmd', '_codex_effort_completion_candidates',
    '_codex_effort_options', '_codex_error_hint', '_codex_fork_cmd', '_codex_model_cmd',
    '_codex_model_completion_candidates', '_codex_models_cmd', '_codex_obj_dict', '_codex_picker_line',
    '_codex_rename_cmd', '_codex_resume_cmd', '_codex_review_cmd', '_codex_runtime_action',
    '_codex_runtime_or_connect', '_codex_sandbox_cmd', '_codex_sandbox_completion_candidates', '_codex_sessions_cmd',
    '_codex_status', '_codex_subcommand_completion_candidates', '_codex_thread_cmd', '_command_completion_sort_key',
    '_command_description', '_compare_cmd', '_complete_after_prefix', '_complete_model_switch',
    '_complete_path_after_prefix', '_complete_path_token', '_complete_prompt_input', '_compute_file_diffs',
    '_configured_mcp_server_ids', '_connect_acp_cmd', '_connect_agent', '_connect_byok_cmd',
    '_connect_byok_mode', '_connect_history', '_connect_last', '_connect_local_cmd',
    '_connect_local_mode', '_connect_previous', '_connect_profile_completion_candidates', '_connect_pure_mode',
    '_context_show_worker', '_conversation_log', '_copy_text_to_clipboard', '_create_checkpoint_before_agent',
    '_current_acp_model_list', '_current_git_diff_sections', '_current_git_diff_text', '_current_interaction_mode_name',
    '_current_session_id', '_current_thinking_state', '_default_harness_wizard_output', '_diff_chunk_approval_id',
    '_diff_file_stats', '_diff_review_entries', '_direct_chat_status', '_discover_acp_agents',
    '_dispatch_connection_profile', '_display_error_result', '_display_file_results', '_display_generic_dict',
    '_display_generic_list', '_display_plan', '_display_success_result', '_display_task_list',
    '_display_todo_list', '_do_exit', '_do_models_update', '_doctor_cmd',
    '_drain_message_queue', '_enqueue_message', '_ensure_approved_tools', '_ensure_input_focus',
    '_ensure_project_trusted_for', '_ensure_pure_mode', '_env_flag', '_exit_sequence_async',
    '_extract_mcp_refs_from_text', '_factory', '_factory_fork_harness', '_factory_fork_model',
    '_factory_help', '_factory_init_policy', '_factory_lineage', '_factory_mode',
    '_factory_policy', '_factory_routes', '_factory_status', '_factory_switch_harness',
    '_factory_switch_model', '_fallback_agents', '_fetch_live_codex_models', '_filter_diff_sections',
    '_find_files', '_find_recipe', '_find_skill_file', '_finish_harness_wizard_flow',
    '_first_completion', '_focus_input_on_ready', '_format_acp_doctor_results', '_format_diff_entry_review',
    '_format_diff_file_index', '_format_diff_review', '_format_free_inference_offers', '_format_live_free_inference',
    '_format_local_smoke_result', '_format_todo_list', '_format_tool_message', '_format_tool_message_rich',
    '_format_tool_output', '_get_claude_models', '_get_codex_models', '_get_emoji_for_line',
    '_get_gemini_models', '_get_opencode_models', '_get_openhands_models', '_get_session_manager',
    '_get_tool_signature', '_go_home', '_grab_clipboard_image', '_grok_api_cmd',
    '_grok_cmd', '_handle_acp_agent_selection', '_handle_agent_question_input', '_handle_agents_discover',
    '_handle_approve', '_handle_byok_model_selection', '_handle_byok_provider_selection', '_handle_checkpoints',
    '_handle_codex_effort_selection', '_handle_codex_model_selection', '_handle_command', '_handle_compact',
    '_handle_context', '_handle_copy', '_handle_diagnostics', '_handle_diff',
    '_handle_edit', '_handle_export', '_handle_factory', '_handle_fork_session',
    '_handle_gemini_event', '_handle_harness_wizard_input', '_handle_history', '_handle_local_connect_start_input',
    '_handle_local_dep_install_input', '_handle_local_model_selection', '_handle_local_provider_selection', '_handle_local_server_start_input',
    '_handle_log_verbosity', '_handle_message', '_handle_modal_permission_result', '_handle_mode_selection',
    '_handle_open', '_handle_opencode_event', '_handle_paste_image', '_handle_permission_auto',
    '_handle_permission_input', '_handle_permissions', '_handle_plan', '_handle_queue',
    '_handle_recommendation_selection', '_handle_redo', '_handle_reject', '_handle_resume_session',
    '_handle_rewind', '_handle_sandbox', '_handle_search', '_handle_select',
    '_handle_session', '_handle_session_resume_selection', '_handle_sessions_command', '_handle_share',
    '_handle_stash', '_handle_switchboard', '_handle_terminal_method', '_handle_theme',
    '_handle_thinking_verbosity', '_handle_timeline', '_handle_trust', '_handle_undo',
    '_handle_update', '_handle_view', '_handle_workspace', '_harness_cmd',
    '_harness_event_preview', '_harness_event_style', '_harness_wizard_choice', '_harness_wizard_cmd',
    '_harness_wizard_next', '_has_superqode_config', '_health_cmd', '_hf_cmd',
    '_hf_coding', '_hf_download', '_hf_endpoints', '_hf_gguf',
    '_hf_info', '_hf_recommend', '_hf_search', '_hf_status',
    '_hf_transformers_status', '_hf_trending', '_hide_prompt_completion_panel', '_hub_cmd',
    '_import_grok_token', '_import_share_artifact', '_in_selection_mode', '_init_animation_manager',
    '_init_config', '_init_sidebar_resize', '_init_undo_manager', '_install_agent',
    '_install_local_dep_then_continue', '_install_pure_permission_bridge', '_is_calm_output', '_is_image_path',
    '_is_known_slash_input', '_is_model_query', '_is_permission_request', '_is_todo_list',
    '_load_agents', '_load_byok_config', '_load_byok_history', '_load_custom_keybindings',
    '_load_local_recipes', '_load_models_dev_data', '_load_recipe_file', '_load_welcome',
    '_local_build', '_local_cmd', '_local_info', '_local_init',
    '_local_labs', '_local_migrate', '_local_models', '_local_pack_init',
    '_local_provider_completion_candidates', '_local_provider_host', '_local_provider_ids', '_local_recommend',
    '_local_scan', '_local_search', '_local_serve', '_local_serve_command',
    '_local_servers', '_local_setup', '_local_skill_names', '_local_smoke',
    '_local_status', '_local_stop', '_local_test', '_local_warm',
    '_looks_like_code', '_looks_like_diff', '_maybe_show_onboarding', '_maybe_show_thinking_hint',
    '_mcp_attach_resource', '_mcp_cmd', '_mcp_id_from_target', '_mcp_resource_completion_candidates',
    '_mcp_resource_ref', '_mcp_server_completion_candidates', '_mcp_server_config_from_target', '_memory_cmd',
    '_memory_status_state', '_mention_completion_candidates', '_mode_cmd', '_mode_picker_items',
    '_model_cmd', '_model_description', '_model_ids_for_provider', '_model_supports_vision',
    '_model_switch_candidates', '_models_cmd', '_models_from_codex_response', '_models_info_cmd',
    '_models_live_render', '_models_search_cmd', '_models_update_cmd', '_move_prompt_completion',
    '_native_local_server_command', '_navigate_to_sidebar_changes', '_normalize_acp_model_id', '_onboarding_marker',
    '_open_diff_entry_file', '_open_diff_review_overlay', '_open_rewind_overlay', '_open_text_overlay',
    '_os_clipboard_copy', '_parse_local_kv_args', '_parse_mcp_resource_ref', '_parse_serve_args',
    '_parse_share_session_and_path', '_parse_switchboard_options', '_parse_yes_no', '_path_candidates_after_prefix',
    '_path_token_candidates', '_perform_rewind', '_permission_risk', '_picker_link_style',
    '_pin_local_prompt_to_input', '_plugins_cmd', '_prewarm_litellm', '_prompt_completion_candidates_for',
    '_prompt_completion_enter_action', '_prompt_file_cmd', '_prompt_interaction_mode', '_prompt_local_connect_start',
    '_provider_completion_candidates', '_provider_description', '_providers_cmd', '_providers_free_cmd',
    '_providers_smoke_cmd', '_queue_selection_digit', '_recipe_cmd', '_recipe_completion_candidates',
    '_recipe_dirs', '_recipe_issues', '_recipe_prompt_text', '_recommend_cmd',
    '_record_ex_command', '_redraw_current_acp_model_picker', '_redraw_local_provider_models', '_refresh_catalog_then_connect_byok',
    '_refresh_harness_panel', '_refresh_plan_status_badge', '_refresh_prompt_mode_label', '_reject_diff_entry',
    '_render_attachments', '_render_compare_results', '_render_harness_wizard_step', '_render_local_server_state',
    '_render_plan_review', '_render_prompt_completion_panel', '_render_queued_input', '_repeat_last_ex_command',
    '_request_runtime_permission', '_rerender_welcome', '_reset_connect_selection_states', '_reset_input_placeholder',
    '_reset_mode_badge_after_role_run', '_resolve_codex_active_model', '_resolve_context_window', '_resolve_export_target',
    '_resolve_mcp_attachment_context', '_resolve_mcp_attachment_context_sync', '_resolve_mcp_resource_ref', '_resolve_share_session_id',
    '_retry_last_message', '_run_acp_jsonrpc_client', '_run_agent_unified', '_run_claude_acp',
    '_run_cli_group', '_run_cli_passthrough', '_run_codex_acp', '_run_fast_agent_cli',
    '_run_local_doctor', '_run_opencode_unified', '_run_openhands_acp', '_run_recipe',
    '_run_shell', '_run_sidebar_terminal_command', '_run_startup_connect', '_run_startup_health_check',
    '_runtime_cmd', '_runtime_completion_candidates', '_runtime_install_message', '_sandbox_cmd',
    '_save_byok_config', '_schedule_picker_visibility', '_scroll_down_to_item', '_scroll_to_highlighted_item',
    '_scroll_to_highlighted_local_model', '_scroll_to_rendered_selected_block', '_scroll_to_vim_search_match', '_search_in_directory',
    '_search_in_file', '_select_by_number_universal', '_select_byok_model_by_number', '_select_model_by_number',
    '_select_picker_number_direct', '_selected_prompt_completion_value', '_send_chat_message', '_send_permission_response',
    '_send_to_agent', '_send_to_pure_mode', '_session_cmd', '_set_approval_mode',
    '_set_byok_model', '_set_cmd', '_set_input_placeholder', '_set_model',
    '_set_prompt_border_title', '_set_prompt_prefill', '_set_skill_enabled', '_set_status_model',
    '_set_status_runtime', '_set_thinking_status', '_set_todos', '_set_todos_from_input',
    '_set_vim_search_highlight', '_setup_picker_handlers', '_share_create', '_share_dir',
    '_share_export', '_share_import', '_share_list', '_share_output_path',
    '_share_revoke', '_should_show_thinking_for_local', '_should_submit_prompt_without_completion', '_show_agent_header',
    '_show_agent_header_with_model', '_show_agents', '_show_agents_async', '_show_antigravity_connect',
    '_show_antigravity_help', '_show_antigravity_migration', '_show_antigravity_status', '_show_beautiful_response',
    '_show_byok_providers', '_show_byok_thinking_line', '_show_calm_summary', '_show_claude_models_selection',
    '_show_codex_effort_picker', '_show_codex_model_picker', '_show_codex_models_selection', '_show_command_output',
    '_show_completion_summary', '_show_connect_picker', '_show_connect_type_picker', '_show_connection_summary',
    '_show_context', '_show_discovered_agents', '_show_error_card', '_show_files',
    '_show_final_outcome', '_show_final_response', '_show_gemini_models_selection', '_show_goodbye_sync',
    '_show_grok_help', '_show_grok_login', '_show_grok_model_picker', '_show_grok_model_picker_async',
    '_show_grok_models', '_show_grok_models_async', '_show_grok_status', '_show_harness_doctor',
    '_show_harness_events', '_show_harness_evidence', '_show_harness_fork', '_show_harness_graph',
    '_show_harness_inspect', '_show_harness_replay', '_show_harness_runs', '_show_harness_status',
    '_show_harness_wizard_help', '_show_help', '_show_local_provider_models', '_show_local_provider_picker',
    '_show_mcp_doctor', '_show_mode_picker', '_show_model_status', '_show_openai_compatible_models',
    '_show_opencode_models_selection', '_show_openhands_models_selection', '_show_permission_alert', '_show_permission_ask',
    '_show_permission_auto_approved', '_show_permission_denied', '_show_permission_modal', '_show_permission_prompt',
    '_show_prompt_completion_panel', '_show_provider_models', '_show_provider_models_picker', '_show_pure_tool_call',
    '_show_pure_tool_result', '_show_recipe_doctor', '_show_recipe_info', '_show_recipes',
    '_show_recipes_doctor', '_show_runtime_picker', '_show_session_resume_picker', '_show_session_tree',
    '_show_sessions', '_show_share_status', '_show_superqode_demo', '_show_switchboard_graph',
    '_show_switchboard_help', '_show_thinking_line', '_show_tools', '_show_trust_status',
    '_show_tui_doctor_dashboard', '_show_welcome', '_show_workflow_center', '_show_workflow_presets',
    '_show_workflow_preview', '_skill_completion_candidates', '_skillopt_cmd', '_skills_cmd',
    '_skills_doctor', '_skills_optimize_cmd', '_split_unified_diff_by_file', '_stage_image_attachment',
    '_start_harness_wizard_flow', '_start_local_server_then_list', '_start_local_then_connect', '_start_models_dev_refresh',
    '_start_permission_pulse', '_start_stream_animation', '_start_thinking', '_startup_health_check',
    '_static_command_candidates', '_stop_permission_pulse', '_stop_stream_animation', '_stop_thinking',
    '_string_tuple', '_strip_ansi', '_suggest_prompt_completion', '_superqode_cli_cmd',
    '_switchboard', '_switchboard_active', '_switchboard_approval_inbox', '_switchboard_children',
    '_switchboard_fork_agent', '_switchboard_handoff', '_switchboard_history', '_switchboard_info',
    '_switchboard_share_tree', '_switchboard_switch', '_sync_approval_mode', '_sync_attachment_prefill',
    '_sync_plan_manager_from_todos', '_teardown_local_model_runtime', '_test_local_connection', '_theme_completion_candidates',
    '_thinking_loop_status', '_tool_needs_permission', '_track_byok_usage', '_trim_transcript_to_user_occurrence',
    '_truncate_mcp_content', '_try_acp_slash_command', '_try_vim_search_input', '_unload_ollama_model',
    '_update_byok_status_bar', '_update_permission_pulse', '_update_prompt_completion_panel', '_update_sidebar_agent_panel',
    '_update_sidebar_context_panel', '_update_sidebar_diff_panel', '_update_sidebar_history_panel', '_update_terminal_title',
    '_usage_cmd', '_use_jsonrpc_acp_client', '_user_message_history', '_version_is_newer',
    '_view_file', '_view_file_info', '_vim_cmd', '_vim_command_history',
    '_vim_enabled', '_vim_search', '_vim_search_feedback', '_vim_search_next',
    '_warmup_ds4', '_warmup_local_generation', '_welcome_width', '_wizard_starters',
    '_work_cmd', '_workflow_cmd', '_workflow_preview_text', '_workflow_provider_model',
    '_workflow_steps_from_spec', '_workflow_timeline_text', '_write_chat_stats', '_write_collapsed_changes_line',
    '_write_share_artifact', 'action_cancel_agent', 'action_clear_screen', 'action_command_palette',
    'action_copy_response', 'action_create_checkpoint', 'action_expand_sidebar', 'action_focus_input',
    'action_leader_key', 'action_navigate_acp_agent_down', 'action_navigate_acp_agent_up', 'action_navigate_acp_model_down',
    'action_navigate_acp_model_up', 'action_navigate_codex_effort_down', 'action_navigate_codex_effort_up', 'action_navigate_codex_model_down',
    'action_navigate_codex_model_up', 'action_navigate_connect_type_down', 'action_navigate_connect_type_up', 'action_navigate_local_model_down',
    'action_navigate_local_model_up', 'action_navigate_local_provider_down', 'action_navigate_local_provider_up', 'action_navigate_mode_down',
    'action_navigate_mode_up', 'action_navigate_model_down', 'action_navigate_model_up', 'action_navigate_opencode_model_down',
    'action_navigate_opencode_model_up', 'action_navigate_provider_down', 'action_navigate_provider_up', 'action_navigate_runtime_down',
    'action_navigate_runtime_up', 'action_navigate_session_resume_down', 'action_navigate_session_resume_up', 'action_open_editor',
    'action_quit', 'action_redo_action', 'action_refresh_byok_models', 'action_refresh_opencode_models',
    'action_rewind', 'action_scroll_log_end', 'action_scroll_log_home', 'action_scroll_log_page_down',
    'action_scroll_log_page_up', 'action_select_highlighted_acp_agent', 'action_select_highlighted_acp_model', 'action_select_highlighted_codex_effort',
    'action_select_highlighted_codex_model', 'action_select_highlighted_connect_type', 'action_select_highlighted_local_model', 'action_select_highlighted_local_provider',
    'action_select_highlighted_mode', 'action_select_highlighted_model', 'action_select_highlighted_opencode_model', 'action_select_highlighted_provider',
    'action_select_highlighted_runtime', 'action_select_highlighted_session_resume', 'action_select_model_1', 'action_select_model_2',
    'action_select_model_3', 'action_select_model_4', 'action_select_model_5', 'action_select_model_6',
    'action_select_model_7', 'action_select_model_8', 'action_select_model_9', 'action_shrink_sidebar',
    'action_sidebar_agent', 'action_sidebar_context', 'action_sidebar_diff', 'action_sidebar_files',
    'action_sidebar_harness', 'action_sidebar_history', 'action_sidebar_terminal', 'action_smart_cancel',
    'action_stash_draft', 'action_toggle_sidebar', 'action_toggle_split_view', 'action_toggle_thinking',
    'action_undo_action', 'agents', 'animation_manager', 'claude_models',
    'codex_models', 'compose', 'gemini_models', 'on_click',
    'on_command_palette_selected', 'on_input_submitted', 'on_key', 'on_leader_key_popup_cancelled',
    'on_leader_key_popup_key_pressed', 'on_mount', 'on_paste', 'on_resizable_divider_resized',
    'on_resize', 'on_sidebar_file_opened', 'on_text_selected', 'on_tree_file_open_requested',
    'opencode_models', 'openhands_models', 'watch_is_busy',
)


def test_superqodeapp_retains_all_baseline_methods():
    from superqode.app_main import SuperQodeApp

    missing = [name for name in BASELINE_METHODS if not hasattr(SuperQodeApp, name)]
    assert not missing, (
        "SuperQodeApp lost %d method(s) during refactor: %s"
        % (len(missing), ", ".join(sorted(missing)[:40]))
    )
