"""Smoke tests for the OpenAI Agents runtime adapter."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List

import pytest

from superqode.agent.loop import AgentConfig
from superqode.runtime import create_runtime
from superqode.runtime.errors import RuntimeNotInstalledError
from superqode.tools.base import Tool, ToolContext, ToolRegistry, ToolResult

pytest.importorskip("agents", reason="openai-agents not installed")

from superqode.runtime.openai_agents import OpenAIAgentsRuntime  # noqa: E402


class _EchoTool(Tool):
    @property
    def name(self) -> str:
        return "echo"

    @property
    def description(self) -> str:
        return "Echo back the input text."

    @property
    def parameters(self) -> Dict[str, Any]:
        return {
            "type": "object",
            "properties": {"text": {"type": "string"}},
            "required": ["text"],
        }

    async def execute(self, args: Dict[str, Any], ctx: ToolContext) -> ToolResult:
        return ToolResult(success=True, output=args.get("text", ""))


def _registry() -> ToolRegistry:
    r = ToolRegistry()
    r.register(_EchoTool())
    return r


def _config(tmp_path: Path) -> AgentConfig:
    return AgentConfig(
        provider="openai",
        model="gpt-4o-mini",
        working_directory=tmp_path,
        enable_session_storage=False,
        session_id="test-oai",
    )


def test_factory_returns_openai_runtime(tmp_path):
    runtime = create_runtime(
        "openai-agents",
        gateway=None,
        tools=_registry(),
        config=_config(tmp_path),
    )
    assert isinstance(runtime, OpenAIAgentsRuntime)
    assert runtime.name == "openai-agents"


def test_runtime_constructs_with_required_fields(tmp_path):
    runtime = OpenAIAgentsRuntime(tools=_registry(), config=_config(tmp_path))
    assert runtime.session_id == "test-oai"
    assert runtime._agent is not None
    assert runtime._run_config.tracing_disabled is True
    # SuperQode echo tool was bridged into the Agent's tool list.
    assert any(getattr(t, "name", "") == "echo" for t in runtime._agent.tools)


def test_runtime_rejects_missing_required(tmp_path):
    with pytest.raises(ValueError):
        OpenAIAgentsRuntime(tools=_registry(), config=None)
    with pytest.raises(ValueError):
        OpenAIAgentsRuntime(tools=None, config=_config(tmp_path))


def test_runtime_ignores_unrelated_kwargs(tmp_path):
    """Constructor parity with BuiltinRuntime — extra kwargs must be tolerated."""
    runtime = OpenAIAgentsRuntime(
        gateway=object(),
        tools=_registry(),
        config=_config(tmp_path),
        mcp_executor=None,
        mcp_tools=[],
        include_mcp=False,
        parallel_tools=True,
        random_unknown="ok",  # collected by **_unused
    )
    assert runtime.name == "openai-agents"


def test_runtime_session_id_autogenerated_when_unset(tmp_path):
    cfg = AgentConfig(
        provider="openai",
        model="gpt-4o-mini",
        working_directory=tmp_path,
        enable_session_storage=False,
    )
    runtime = OpenAIAgentsRuntime(tools=_registry(), config=cfg)
    assert runtime.session_id.startswith("oai-")


def test_runtime_jsonl_session_enabled_when_storage_on(tmp_path):
    cfg = AgentConfig(
        provider="openai",
        model="gpt-4o-mini",
        working_directory=tmp_path,
        enable_session_storage=True,
        session_storage_dir=str(tmp_path / "sess"),
        session_id="t1",
    )
    runtime = OpenAIAgentsRuntime(tools=_registry(), config=cfg)
    assert runtime._session is not None
    assert runtime._session.session_id == "t1"


def test_cancel_sets_flag(tmp_path):
    runtime = OpenAIAgentsRuntime(tools=_registry(), config=_config(tmp_path))
    assert runtime._cancelled is False
    runtime.cancel()
    assert runtime._cancelled is True
    runtime.reset_cancellation()
    assert runtime._cancelled is False


def test_non_openai_provider_uses_litellm_wrapper(tmp_path):
    """If the user picks a non-openai provider, the model spec must be a LitellmModel."""
    from agents.extensions.models.litellm_model import LitellmModel

    cfg = AgentConfig(
        provider="anthropic",
        model="claude-sonnet-4-6",
        working_directory=tmp_path,
        enable_session_storage=False,
    )
    runtime = OpenAIAgentsRuntime(tools=_registry(), config=cfg)
    assert isinstance(runtime._agent.model, LitellmModel)


def test_openai_provider_passes_bare_model_string(tmp_path):
    runtime = OpenAIAgentsRuntime(tools=_registry(), config=_config(tmp_path))
    # gpt-4o-mini as a bare string id
    assert runtime._agent.model == "gpt-4o-mini"


def test_translate_result_returns_agent_response_shape(tmp_path):
    """Translate a fabricated RunResult-like object through _translate_result."""
    runtime = OpenAIAgentsRuntime(tools=_registry(), config=_config(tmp_path))

    class _FakeResult:
        new_items: List[Any] = []
        raw_responses: List[Any] = []
        interruptions: List[Any] = []
        final_output = "all done"

    resp = runtime._translate_result(prompt="hi", result=_FakeResult())
    assert resp.content == "all done"
    assert resp.stopped_reason == "complete"
    assert resp.tool_calls_made == 0
    assert resp.messages[0].role == "user"
    assert resp.messages[0].content == "hi"


def test_translate_result_flags_needs_approval_when_interruptions_present(tmp_path):
    runtime = OpenAIAgentsRuntime(tools=_registry(), config=_config(tmp_path))

    class _FakeResult:
        new_items: List[Any] = []
        raw_responses: List[Any] = []
        interruptions = ["pretend approval item"]
        final_output = ""

    fake = _FakeResult()
    resp = runtime._translate_result(prompt="run a thing", result=fake)
    assert resp.stopped_reason == "needs_approval"
    # The RunState (here our fake) is stashed for the TUI to resume.
    assert runtime.pending_state is fake


def test_list_runtimes_reports_openai_installed_when_available():
    from superqode.runtime import list_runtimes

    info = {r.name: r for r in list_runtimes()}
    assert info["openai-agents"].installed is True
    assert info["openai-agents"].implemented is True
