"""Smoke tests for the ADK runtime adapter.

Skipped when google-adk is not installed.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from superqode.agent.loop import AgentConfig
from superqode.runtime import create_runtime
from superqode.runtime.errors import RuntimeNotInstalledError
from superqode.tools.base import ToolRegistry

pytest.importorskip("google.adk", reason="google-adk not installed; skipping ADK runtime tests")

# Imports below only execute when google-adk is available.
from superqode.runtime.adk import ADKRuntime  # noqa: E402


def _config(tmp_path: Path) -> AgentConfig:
    return AgentConfig(
        provider="openai",
        model="gpt-4o-mini",
        working_directory=tmp_path,
        # Avoid touching real disk for session storage.
        enable_session_storage=False,
        session_id="test-adk",
    )


def test_factory_returns_adk_runtime(tmp_path):
    runtime = create_runtime(
        "adk",
        gateway=None,
        tools=ToolRegistry.full(),
        config=_config(tmp_path),
    )
    assert isinstance(runtime, ADKRuntime)
    assert runtime.name == "adk"


def test_adk_runtime_constructs_with_required_fields(tmp_path):
    runtime = create_runtime(
        "adk",
        gateway=None,
        tools=ToolRegistry.full(),
        config=_config(tmp_path),
    )
    assert runtime.session_id == "test-adk"
    # The bridged LlmAgent is built lazily inside __init__.
    assert runtime._agent is not None
    assert runtime._runner is not None


def test_adk_runtime_rejects_missing_config(tmp_path):
    with pytest.raises(ValueError):
        ADKRuntime(tools=ToolRegistry.full(), config=None)
    with pytest.raises(ValueError):
        ADKRuntime(tools=None, config=_config(tmp_path))


def test_adk_runtime_ignores_unrelated_kwargs(tmp_path):
    # Constructor parity with BuiltinRuntime: extra kwargs the builtin uses
    # (mcp_executor, mcp_tools, include_mcp, gateway) should not raise.
    runtime = ADKRuntime(
        gateway=object(),  # ignored
        tools=ToolRegistry.full(),
        config=_config(tmp_path),
        mcp_executor=None,
        mcp_tools=[],
        include_mcp=False,
        parallel_tools=True,
        random_unknown="ok",  # collected by **_unused
    )
    assert runtime.name == "adk"


def test_adk_runtime_exposes_cancel(tmp_path):
    runtime = ADKRuntime(tools=ToolRegistry.full(), config=_config(tmp_path))
    assert runtime._cancelled is False
    runtime.cancel()
    assert runtime._cancelled is True
    runtime.reset_cancellation()
    assert runtime._cancelled is False


def test_adk_runtime_session_id_autogenerated_when_unset(tmp_path):
    config = AgentConfig(
        provider="openai",
        model="gpt-4o-mini",
        working_directory=tmp_path,
        enable_session_storage=False,
    )
    runtime = ADKRuntime(tools=ToolRegistry.full(), config=config)
    assert runtime.session_id.startswith("adk-")
