"""
A2A Protocol Types - Reimplemented from spec (no copying from reference).

Agent2Agent (A2A) Protocol: https://a2a.ai
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional


class TaskStatusValue(str, Enum):
    SUBMITTED = "submitted"
    WORKING = "working"
    INPUT_REQUIRED = "input_required"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELED = "canceled"
    REJECTED = "rejected"


class MessageRole(str, Enum):
    USER = "user"
    AGENT = "agent"


class PartType(str, Enum):
    TEXT = "text"
    FILE = "file"
    DATA = "data"


@dataclass
class TextPart:
    """Text content in a message part."""

    text: str
    mime_type: Optional[str] = None


@dataclass
class FilePart:
    """File reference in a message part."""

    url: Optional[str] = None
    mime_type: Optional[str] = None
    filename: Optional[str] = None


@dataclass
class DataPart:
    """Structured data in a message part."""

    data: Dict[str, Any]


@dataclass
class Part:
    """Single content unit in a message or artifact."""

    text: Optional[str] = None
    file: Optional[FilePart] = None
    data: Optional[Dict[str, Any]] = None
    mime_type: Optional[str] = None
    filename: Optional[str] = None
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class Message:
    """A single turn in conversation between client and agent."""

    role: MessageRole
    parts: List[Part] = field(default_factory=list)
    message_id: Optional[str] = None


@dataclass
class Artifact:
    """Tangible output generated by an agent."""

    parts: List[Part] = field(default_factory=list)
    artifact_id: Optional[str] = None
    name: Optional[str] = None
    mime_type: Optional[str] = None
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class TaskStatus:
    """Current state of a task."""

    state: TaskStatusValue
    message: Optional[str] = None
    agent_name: Optional[str] = None


@dataclass
class Task:
    """Stateful unit of work with unique ID and lifecycle."""

    task_id: str
    status: TaskStatus
    history: List[Message] = field(default_factory=list)
    artifacts: List[Artifact] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)
    context_id: Optional[str] = None


@dataclass
class AgentCapabilities:
    """Optional capabilities supported by an agent."""

    streaming: bool = False
    push_notifications: bool = False
    extended_agent_card: bool = False


@dataclass
class AgentProvider:
    """Information about the agent provider."""

    organization: str
    url: Optional[str] = None


@dataclass
class AgentSkill:
    """A skill/capability of an agent."""

    id: str
    name: str
    description: str
    tags: List[str] = field(default_factory=list)
    examples: List[str] = field(default_factory=list)


@dataclass
class AgentCard:
    """JSON metadata document for agent discovery."""

    name: str
    description: str
    url: str  # A2A server endpoint
    version: str
    capabilities: AgentCapabilities = field(default_factory=AgentCapabilities)
    provider: Optional[AgentProvider] = None
    documentation_url: Optional[str] = None
    icon_url: Optional[str] = None
    skills: List[AgentSkill] = field(default_factory=list)
    supported_interfaces: List[Dict[str, str]] = field(default_factory=list)
    default_input_modes: List[str] = field(default_factory=lambda: ["text"])
    default_output_modes: List[str] = field(default_factory=lambda: ["text"])


@dataclass
class SendMessageRequest:
    """Request to send a message to an agent."""

    message: Message
    session_id: Optional[str] = None
    task_id: Optional[str] = None  # For continuing existing task


@dataclass
class SendMessageResponse:
    """Response from sending a message."""

    task: Optional[Task] = None
    message: Optional[Message] = None  # For immediate responses


@dataclass
class StreamResponse:
    """Streaming response event."""

    type: str  # "message", "task", "error", "done"
    data: Any


@dataclass
class PushNotificationConfig:
    """Configuration for push notifications."""

    url: str
    token: Optional[str] = None
    authentication: Optional[Dict[str, str]] = None


# Utility functions
def create_text_message(
    role: MessageRole, content: str, message_id: Optional[str] = None
) -> Message:
    """Create a simple text message."""
    part = Part(text=content, mime_type="text/plain")
    return Message(role=role, parts=[part], message_id=message_id)


def create_agent_card(
    name: str,
    description: str,
    url: str,
    version: str = "1.0",
    streaming: bool = True,
    skills: Optional[List[Dict[str, str]]] = None,
) -> AgentCard:
    """Create an AgentCard with common defaults."""
    capabilities = AgentCapabilities(streaming=streaming)

    agent_skills = []
    if skills:
        for s in skills:
            agent_skills.append(
                AgentSkill(
                    id=s.get("id", ""),
                    name=s.get("name", ""),
                    description=s.get("description", ""),
                    tags=s.get("tags", []),
                    examples=s.get("examples", []),
                )
            )

    return AgentCard(
        name=name,
        description=description,
        url=url,
        version=version,
        capabilities=capabilities,
        skills=agent_skills,
    )
