"""
SuperQode App Constants - Theme, Icons, Colors, and Messages.
"""

# Clean ASCII art for SUPERQODE - Standard style (upright, thin)
ASCII_LOGO = """
 ____  _   _ ____  _____ ____   ___    ___  ____  _____
/ ___|| | | |  _ \\| ____|  _ \\ / _ \\  / _ \\|  _ \\| ____|
\\___ \\| | | | |_) |  _| | |_) | | | || | | | | | |  _|
 ___) | |_| |  __/| |___|  _ <| |_| || |_| | |_| | |___
|____/ \\___/|_|   |_____|_| \\_\\\\__\\_\\ \\___/|____/|_____|
"""

# Compact logo for header
COMPACT_LOGO = """ ____  _   _ ____  _____ ____   ___    ___  ____  _____
|____/ \\___/|_|   |_____|_| \\_\\\\__\\_\\ \\___/|____/|_____|"""

# Compact positioning used by alternate TUI renderers.
TAGLINE_PART1 = "The Harness Layer for Coding Agents"
TAGLINE_PART2 = "Build or connect · Open or proprietary · Local or hosted"

# First-page order for the product-level connection choices.
CONNECT_COMPLETION_COMMANDS = (
    ":connect",
    ":connect local",
    ":connect acp",
    ":connect byok",
    ":connect subscriptions",
    ":connect other-harnesses",
    ":connect codex",
    ":connect grok",
    ":connect copilot",
    ":connect copilot-cli",
    ":connect antigravity",
    ":connect devin",
    ":connect glm-cli",
    ":connect zai",
)

# Normal purple → pink → orange gradient for ASCII logo
GRADIENT = ["#7c3aed", "#a855f7", "#c084fc", "#ec4899", "#f97316", "#fb923c"]

# Rainbow gradient for animations
RAINBOW = ["#ef4444", "#f97316", "#eab308", "#22c55e", "#06b6d4", "#3b82f6", "#8b5cf6", "#ec4899"]

THEME = {
    "bg": "#000000",
    "surface": "#000000",
    "surface2": "#0a0a0a",
    "border": "#1a1a1a",
    "border_active": "#2a2a2a",
    "purple": "#a855f7",
    "user_prompt_bg": "#20162e",
    "magenta": "#d946ef",
    "pink": "#ec4899",
    "rose": "#fb7185",
    "orange": "#f97316",
    "gold": "#fbbf24",
    "yellow": "#eab308",
    "cyan": "#06b6d4",
    "teal": "#14b8a6",
    "green": "#22c55e",
    "success": "#22c55e",
    "error": "#ef4444",
    "warning": "#f59e0b",
    "text": "#e4e4e7",
    # Secondary text must stay readable: #71717a measured 4.35:1 on the
    # black surface, below the 4.5:1 needed for body text. Same zinc
    # family, one step up, now 8.19:1. No brand colour changes.
    "muted": "#a1a1aa",
    # Tertiary/decorative text. #52525b measured 2.72:1, effectively
    # unreadable; #71717a gives 4.35:1, comfortably above the 3:1 floor
    # for non-essential text.
    "dim": "#71717a",
    # Clickable text that carries no state of its own. A link that also carries
    # state (ready, destructive) keeps its own colour instead.
    "link": "#a855f7",
}

# Rich emoji set for different contexts
ICONS = {
    # Status
    "done": "✓",
    "pending": "○",
    "active": "●",
    "error": "✗",
    "warning": "⚠",
    "success": "✅",
    "fail": "❌",
    "loading": "◌",
    # Navigation
    "home": "🏠",
    "back": "←",
    "forward": "→",
    "up": "↑",
    "down": "↓",
    # Actions
    "run": "▶",
    "stop": "■",
    "pause": "⏸",
    "refresh": "🔄",
    "search": "🔍",
    # Objects
    "file": "📄",
    "folder": "📁",
    "code": "💻",
    "terminal": "🖥️",
    "shell": "$",
    "link": "🔗",
    "key": "🔑",
    "lock": "🔒",
    "unlock": "🔓",
    # Team & Agents
    "team": "👥",
    "robot": "🤖",
    "brain": "🧠",
    "qa": "🧪",
    "user": "👤",
    "agent": "🤖",
    # Communication
    "task": "📋",
    "handoff": "🔄",
    "context": "📎",
    "message": "💬",
    "send": "📤",
    "receive": "📥",
    "chat": "💭",
    # Effects
    "spark": "✨",
    "magic": "🪄",
    "rocket": "🚀",
    "crystal": "🔮",
    "zap": "⚡",
    "bulb": "💡",
    "target": "🎯",
    "fire": "🔥",
    "star": "⭐",
    "gem": "💎",
    "crown": "👑",
    "trophy": "🏆",
    # Emotions
    "heart": "💜",
    "wave": "👋",
    "eyes": "👀",
    "think": "🤔",
    "celebrate": "🎉",
    "cool": "😎",
    "thumbsup": "👍",
    # Technical
    "api": "🔌",
    "database": "🗄️",
    "cloud": "☁️",
    "server": "🖥️",
    "git": "📦",
    "docker": "🐳",
    "test": "🧪",
    "bug": "🐛",
    # Help
    "help": "❓",
    "info": "ℹ️",
    "tip": "💡",
    "exit": "👋",
}

# 14 Official ACP Agents - Colors
AGENT_COLORS = {
    # Tier 1 - Major Agents
    "gemini": "#4285f4",  # Google Blue
    "claude": "#d97706",  # Anthropic Orange
    "claude-code": "#d97706",  # Anthropic Orange
    "codex": "#10b981",  # Green
    "grok": "#e5e7eb",  # xAI neutral, readable on the dark TUI
    "devin": "#93c5fd",  # Cognition navy, lightened for the dark TUI
    "junie": "#fe315d",  # JetBrains Pink
    "goose": "#8b5cf6",  # Block Purple
    "kimi": "#5b21b6",  # Moonshot Deep Purple
    "opencode": "#22c55e",  # Open Source Green
    # Tier 2 - Community Agents
    "stakpak": "#0ea5e9",  # Sky Blue
    "vtcode": "#f59e0b",  # Amber
    "auggie": "#ec4899",  # Pink
    "code-assistant": "#f97316",  # Rust Orange
    "cagent": "#6366f1",  # Indigo
    "fast-agent": "#14b8a6",  # Teal
    "llmling-agent": "#a855f7",  # Purple
}

# 14 Official ACP Agents - Icons
AGENT_ICONS = {
    # Tier 1 - Major Agents
    "gemini": "✨",  # Sparkles - Google Gemini's multimodal nature
    "claude": "🧡",  # Orange heart - Anthropic's warm AI
    "claude-code": "🧡",  # Orange heart - Anthropic's warm AI
    "codex": "📜",  # Scroll
    "grok": "G",  # Grok Build
    "devin": "👷",  # Construction worker - Cognition's autonomous engineer
    "junie": "🧠",  # Brain - JetBrains intelligence
    "goose": "🦆",  # Duck - Block's Goose
    "kimi": "🌙",  # Moon - Moonshot AI's Kimi
    "opencode": "🌿",  # Seedling - open source growth
    # Tier 2 - Community Agents
    "stakpak": "📦",  # Package - code packages
    "vtcode": "⚡",  # Lightning - versatile & fast
    "auggie": "🔮",  # Crystal ball - Augment's AI vision
    "code-assistant": "🦀",  # Crab - Rust language
    "cagent": "🤖",  # Robot - multi-agent orchestration
    "fast-agent": "🚀",  # Rocket - fast workflows
    "llmling-agent": "🔗",  # Link - framework connections
}

# Rich thinking messages with emojis - FUN & ENGAGING!
THINKING_MSGS = [
    # Classic thinking
    ("🧠 Analyzing your request", "brain"),
    ("🔍 Understanding context", "search"),
    ("💭 Thinking deeply", "think"),
    ("⚙️ Processing information", "gear"),
    # Fun & playful
    ("🎪 Juggling possibilities", "circus"),
    ("🎨 Painting a solution", "art"),
    ("🧩 Piecing together the puzzle", "puzzle"),
    ("🎭 Getting into character", "theater"),
    ("🎲 Rolling for initiative", "dice"),
    ("🎸 Jamming on your code", "music"),
    ("🎬 Directing the scene", "movie"),
    ("🎡 Spinning up ideas", "wheel"),
    # Food & cooking
    ("👨‍🍳 Cooking up something special", "chef"),
    ("🍳 Frying some fresh code", "cooking"),
    ("🥘 Simmering the solution", "stew"),
    ("🍕 Serving hot code", "pizza"),
    ("☕ Brewing the perfect response", "coffee"),
    # Space & science
    ("🚀 Launching into action", "rocket"),
    ("🌟 Aligning the stars", "stars"),
    ("🔭 Scanning the codeverse", "telescope"),
    ("⚛️ Splitting atoms of logic", "atom"),
    ("🌌 Exploring the galaxy", "galaxy"),
    ("🛸 Beaming down answers", "ufo"),
    # Magic & fantasy
    ("🪄 Casting a spell", "magic"),
    ("🔮 Consulting the crystal ball", "crystal"),
    ("✨ Sprinkling some magic", "sparkle"),
    ("🧙 Wizarding up a solution", "wizard"),
    ("🦄 Summoning unicorn power", "unicorn"),
    ("🐉 Awakening the code dragon", "dragon"),
    # Tech & coding
    ("💻 Compiling thoughts", "computer"),
    ("🔧 Tightening the bolts", "wrench"),
    ("⚡ Supercharging neurons", "lightning"),
    ("🔥 Firing up the engines", "fire"),
    ("💡 Light bulb moment incoming", "bulb"),
    ("🎯 Locking onto target", "target"),
    # Nature & animals
    ("🐝 Busy as a bee", "bee"),
    ("🦊 Being clever like a fox", "fox"),
    ("🐙 Multitasking like an octopus", "octopus"),
    ("🦅 Eagle-eye analyzing", "eagle"),
    ("🐢 Slow and steady wins", "turtle"),
    # Sports & action
    ("🏃 Sprinting to the finish", "runner"),
    ("🎳 Bowling a strike", "bowling"),
    ("🏄 Riding the code wave", "surf"),
    ("⛷️ Skiing through logic", "ski"),
    ("🎿 Slaloming past bugs", "slalom"),
    # Building & crafting
    ("🏗️ Constructing the answer", "construction"),
    ("🧱 Building brick by brick", "bricks"),
    ("🪚 Carving out a solution", "saw"),
    ("🎨 Masterpiece in progress", "palette"),
    ("📐 Measuring twice, coding once", "ruler"),
    # Celebration vibes
    ("🎉 Party in the processor", "party"),
    ("🎊 Confetti of creativity", "confetti"),
    ("🥳 Getting excited about this", "celebrate"),
    ("💃 Dancing through the code", "dance"),
    ("🕺 Grooving to the algorithm", "groove"),
]

# Commands for autocompletion - ordered by priority (most common first)
COMMANDS = [
    ":connect",
    ":connect agents",
    ":connect harness",
    ":connect models",
    ":connect build",
    ":connect local",
    ":connect acp",
    ":connect byok",
    ":connect plan",
    ":connect build-import",
    ":connect build-preset",
    ":connect build-wizard",
    ":connect build-blank",
    ":connect subscriptions",
    ":connect other-harnesses",
    ":explore",
    ":explore agents",
    ":explore providers",
    ":explore local",
    ":explore harnesses",
    ":explore runtimes",
    ":explore memory",
    ":explore tools",
    ":explore sandboxes",
    ":explore observability",
    ":explore evaluation",
    ":explore optimization",
    ":explore remote",
    ":explore delivery",
    ":capabilities",
    ":eval",
    ":evals",
    ":tour",
    ":tour next",
    ":connect codex",
    ":connect cursor",
    ":connect amp",
    ":connect antigravity",
    ":connect grok",
    ":connect copilot",
    ":connect devin",
    ":connect droid",
    ":connect kiro",
    ":connect glm-cli",
    ":connect qwen-code",
    ":connect kimi-code",
    ":connect acp featured",
    ":connect acp enterprise",
    ":connect acp all",
    ":connect acp refresh",
    # Compatibility shortcuts. These stay accepted but do not appear in the
    # subscription picker because they are ACP/BYOK implementation routes.
    ":connect copilot-cli",
    ":connect zai",
    ":claude",
    ":claude status",
    ":claude model",
    ":claude permission",
    ":claude sessions",
    ":claude commands",
    ":claude review",
    ":antigravity",
    ":antigravity status",
    ":antigravity managed",
    ":antigravity migrate",
    ":antigravity launch",
    ":muse",
    ":muse login",
    ":muse status",
    ":muse-code",
    ":pipy",
    ":pipy help",
    ":pipy compact",
    ":pipy tree",
    ":pipy fork",
    ":pipy resume",
    ":pipy new",
    ":pipy name",
    ":pipy model",
    ":pipy session",
    ":pipy export",
    ":pipy skill",
    ":pipy prompt",
    ":rlm",
    ":rlm help",
    ":rlm status",
    ":rlm attach",
    ":rlm detach",
    ":rlm stop",
    ":rlm session",
    ":rlm policy",
    ":rlm goal",
    ":rlm autonomous",
    ":rlm sandbox",
    ":rlm usage",
    ":rlm agents",
    ":rlm send",
    ":rlm steer",
    ":rlm cancel",
    ":rlm compact",
    ":rlm tree",
    ":rlm fork",
    ":rlm export",
    ":pi",
    ":agy",
    ":agy help",
    ":agy connect",
    ":agy status",
    ":agy agents",
    ":agy agent",
    ":agy models",
    ":agy model",
    ":agy effort",
    ":agy changelog",
    ":agy plugin",
    ":agy plugin list",
    ":agy plugin import",
    ":agy plugin install",
    ":agy plugin uninstall",
    ":agy plugin enable",
    ":agy plugin disable",
    ":agy plugin validate",
    ":agy plugin link",
    ":agy update",
    ":agy install",
    ":agy launch",
    ":grok",
    ":grok connect",
    ":grok models",
    ":grok model",
    ":grok status",
    ":grok login",
    ":grok api",
    ":prime",
    ":prime-agent",
    ":prime help",
    ":prime connect",
    ":prime models",
    ":prime local",
    ":prime depth",
    ":prime goal",
    ":prime autonomous",
    ":prime agents",
    ":prime schedule",
    ":prime packages",
    ":prime status",
    ":prime doctor",
    ":prime update",
    ":prime login",
    ":exit",
    ":quit",
    ":help",
    ":keys",
    ":search",
    ":edit",
    ":vim",
    ":vim on",
    ":vim off",
    ":vim tutor",
    ":set vim",
    ":set novim",
    ":w",
    ":e",
    ":ls",
    ":grep",
    ":clear",
    ":agents",
    ":agents connect",
    ":agents connect opencode",
    ":agents list",
    ":agents refresh",
    ":agents doctor",
    ":agents show",
    ":agents store",
    ":agents install",
    ":agents free-models",
    ":agents model",
    ":providers",
    ":providers list",
    ":providers doctor",
    ":providers models",
    ":providers guide",
    ":providers recommend",
    ":providers smoke",
    ":providers scan-free",
    ":providers test",
    ":providers monty",
    ":providers ds4",
    ":providers mlx",
    ":providers free",
    ":providers free --live",
    ":providers free --live openrouter",
    ":providers free --live models-dev",
    ":providers free --live litellm",
    ":providers use",
    ":providers show",
    ":connect setup",
    ":context",
    ":chat",
    ":chat off",
    ":chat clear",
    ":build",
    ":mode",
    ":mode chat",
    ":mode build",
    ":mode plan",
    ":hub",
    ":hub off",
    ":disconnect",
    # Runtime backend selection (see ':runtime list' for status)
    ":runtime",
    ":runtime list",
    ":runtime setup",
    ":runtime builtin",
    ":runtime adk",
    ":runtime openai-agents",
    ":runtime pydanticai",
    ":runtime codex-sdk",
    ":runtime copilot-sdk",
    ":runtime doctor",
    ":codex",
    ":codex status",
    ":codex models",
    ":codex model",
    ":codex effort",
    ":codex sandbox",
    ":codex review",
    ":codex compact",
    ":codex thread",
    ":codex sessions",
    ":codex resume",
    ":codex fork",
    ":codex rename",
    ":codex archive",
    ":codex account",
    ":codex logout",
    ":copilot",
    ":copilot login",
    ":copilot sdk",
    ":copilot cli",
    ":copilot status",
    ":copilot models",
    ":copilot model",
    ":copilot mode",
    ":copilot sessions",
    ":copilot resume",
    ":copilot version",
    ":copilot help",
    ":tau",
    ":tau help",
    ":tau use",
    ":tau login",
    ":tau status",
    ":tau providers",
    ":tau models",
    ":tau model",
    ":tau sessions",
    ":tau logout",
    ":tau retry",
    ":files",
    ":find",
    ":sidebar",
    ":sodebar",
    ":toggle_thinking",
    ":home",
    # Init command
    ":init",
    ":config",
    ":config init",
    ":config show",
    ":config validate",
    ":config set",
    ":config get",
    ":auth",
    ":auth info",
    ":auth check",
    ":auth login",
    ":auth logout",
    ":auth list",
    ":serve",
    ":serve status",
    ":serve web",
    ":serve harness",
    ":serve api",
    ":serve acp",
    ":serve a2a",
    ":profiles",
    ":profiles list",
    ":doctor",
    ":daemon",
    # Coding agent commands
    ":approve",
    ":approve all",
    ":reject",
    ":reject all",
    ":permissions",
    ":policy",
    ":diff",
    ":diff files",
    ":diff split",
    ":diff unified",
    ":plan",
    ":plan on",
    ":plan off",
    ":plan status",
    ":plan run",
    ":plan approve",
    ":plan edit",
    ":plan review",
    ":plan reject",
    ":plan clear",
    ":undo",
    ":history",
    ":history clear",
    ":transcript",
    ":timeline",
    ":rewind",
    ":tree",
    ":switchboard",
    ":sw",
    ":switchboard graph",
    ":switchboard switch",
    ":switchboard info",
    ":switchboard history",
    ":switchboard children",
    ":switchboard handoff",
    ":switchboard fork-agent",
    ":switchboard approvals",
    ":switchboard share-tree",
    ":factory",
    ":factory init-policy",
    ":factory policy",
    ":factory routes",
    ":factory status",
    ":factory resolve-route",
    ":factory mode",
    ":factory mode no-subscription",
    ":factory mode private",
    ":factory mode cheap",
    ":factory mode best",
    ":factory switch-model",
    ":factory switch-harness",
    ":factory fork-model",
    ":factory fork-harness",
    ":factory lineage",
    ":work create",
    ":work add-task",
    ":work list",
    ":work status",
    ":work usage",
    ":work policy",
    ":work tree",
    ":work queue",
    ":work run",
    ":work worker",
    ":work workers",
    ":work watch",
    ":policy init",
    ":policy show",
    ":policy explain",
    ":work claim",
    ":work heartbeat",
    ":work complete",
    ":work fail",
    ":work recover",
    ":work resume",
    ":work check",
    ":work artifact-add",
    ":work artifacts",
    ":work events",
    ":work prepare",
    ":work diff",
    ":work approve",
    ":work merge",
    ":work rollback",
    ":work cleanup",
    ":work reject",
    ":work cancel",
    ":share",
    ":share create",
    ":share export",
    ":share import",
    ":share list",
    ":share revoke",
    ":trust",
    ":trust status",
    ":trust yes",
    ":trust no",
    ":trust doctor",
    ":theme",
    ":export",
    ":export html",
    ":export markdown",
    ":export json",
    ":compare",
    ":benchmark",
    ":benchmark run",
    ":sandbox",
    ":sandbox doctor",
    ":sandbox run",
    ":paste",
    ":queue",
    ":queue clear",
    ":stash",
    ":stash list",
    ":stash clear",
    ":session",
    ":session rename",
    ":sessions",
    ":sessions resume",
    ":sessions list",
    ":sessions tree",
    ":sessions graph",
    ":sessions switch",
    ":sessions info",
    ":sessions history",
    ":sessions children",
    ":sessions handoff",
    ":sessions fork-agent",
    ":sessions show",
    ":sessions export",
    ":sessions delete",
    ":resume",
    ":update",
    # File viewer commands
    ":view",
    ":view info",
    ":search",
    ":tools",
    ":tools list",
    ":tools minimal",
    ":tools standard",
    ":tools full",
    ":plugins",
    ":plugins list",
    ":plugins show",
    ":plugins validate",
    ":plugins doctor",
    ":plugins add",
    ":plugins enable",
    ":plugins disable",
    ":memory",
    ":memory status",
    ":memory providers",
    ":memory doctor",
    ":memory remember",
    ":memory search",
    ":memory forget",
    ":memory export",
    ":local",
    ":local doctor",
    ":local guardrails",
    ":local setup",
    ":local init",
    ":local build",
    ":local packs",
    ":local pack",
    ":local pack init",
    ":local bench",
    ":local migrate",
    ":local optimize",
    ":local search",
    ":local smoke",
    ":local labs",
    ":local serve",
    ":local servers",
    ":local models",
    ":local stop",
    ":local warm",
    ":local airplane prepare",
    ":local airplane",
    ":local airplane doctor",
    ":local airplane smoke",
    ":local airplane index",
    ":local airplane models",
    ":local airplane health",
    ":skills",
    ":skills list",
    ":skills info",
    ":skills search",
    ":skills add",
    ":skills import",
    ":skills doctor",
    ":skills optimize",
    ":skills enable",
    ":skills disable",
    ":skills remove",
    ":skillopt",
    ":skillopt export",
    ":skillopt check",
    ":recipes",
    ":recipes list",
    ":recipe",
    ":recipe list",
    ":recipe info",
    ":recipe run",
    ":recipe doctor",
    ":harness",
    ":harness list",
    ":harness current",
    ":harness show",
    ":harness use",
    ":harness switch",
    ":harness all",
    ":harness customize",
    ":harness status",
    ":harness inspect",
    ":harness doctor",
    ":harness graph",
    ":harness replay",
    ":harness fork",
    ":harness evidence",
    ":harness events",
    ":harness runs",
    ":harness templates",
    ":harness wizard",
    ":harness init",
    ":harness validate",
    ":harness explain",
    ":harness compile",
    ":harness diff",
    ":harness run",
    ":harness test",
    ":harness eval",
    ":harness bench",
    ":harness bench-verify",
    ":harness promote",
    ":harness promote stage",
    ":harness promote canary",
    ":harness promote activate",
    ":harness promote rollback",
    ":harness promote status",
    ":harness promote select",
    ":harness eval-packs",
    ":harness auto-bench",
    ":harness list-backends",
    ":harness list-templates",
    ":harness protocol",
    ":harness protocol list",
    ":harness protocol describe",
    ":harness protocol conformance",
    ":harness import-agent",
    ":harness import-omnigent",
    ":harness registry",
    ":harness registry list",
    ":harness registry publish",
    ":harness registry install",
    ":harness inbox",
    ":harness inbox add",
    ":harness inbox list",
    ":harness inbox recover",
    ":harness drain",
    ":harness worker",
    ":harness observability",
    ":harness observability status",
    ":harness observability export",
    ":harness mine-failures",
    ":harness logbook",
    ":harness logbook update",
    ":harness logbook show",
    ":harness logbook export",
    ":harness logbook prune",
    ":harness audit-candidate",
    ":harness candidates",
    ":harness candidates list",
    ":harness candidates show",
    ":harness candidates export",
    ":harness improve",
    ":harness optimize",
    ":harness optimize-omni",
    ":harness optimize-inspect",
    ":harness optimize-ledger",
    ":workflow",
    ":workflow status",
    ":workflow presets",
    ":workflow preview",
    ":workflow doctor",
    ":workflow run",
    ":attach",
    ":attach list",
    ":attach remove",
    ":attach clear",
    ":prompt",
    ":models",
    ":models providers",
    ":models show",
    ":models hub",
    ":models download",
    ":models convert-mlx",
    ":models cached",
    ":models rm",
    # Copy/Open commands
    ":copy",
    ":copy response",
    ":copy transcript",
    ":select",
    ":select response",
    ":select transcript",
    ":open",
    # MCP commands
    ":mcp",
    ":mcp list",
    ":mcp status",
    ":mcp tools",
    ":mcp resources",
    ":mcp prompts",
    ":mcp connect",
    ":mcp disconnect",
    ":mcp reconnect",
    ":mcp add",
    ":mcp doctor",
    ":mcp attach",
    ":model",
    ":model doctor",
    ":model switch",
    ":model reasoning",
    ":model temperature",
    ":doctor tui",
    # Approval mode commands
    ":mode auto",
    ":mode ask",
    ":mode deny",
    ":mode",
]

# Root aliases accepted by ``SlashCommandMixin._handle_command``.  Keep these
# visible in completion even when the canonical command already appears above;
# the completion catalog de-duplicates them while preserving priority order.
TUI_COMMAND_ALIASES = [
    ":a2a",
    ":acp",
    ":agent",
    ":benchmarks",
    ":catalog",
    ":checkpoints",
    ":clone",
    ":compact",
    ":demo",
    ":diagnostics",
    ":doctor-current",
    ":edit",
    ":fork",
    ":health",
    ":hf",
    ":image",
    ":img",
    ":log",
    ":m",
    ":model-guide",
    ":plugin",
    ":provider",
    ":q",
    ":recommend",
    ":redo",
    ":retry",
    ":sessions-current",
    ":status",
    ":summary",
    ":thinking",
    ":usage",
    ":work",
    ":workflows",
    ":workspace",
    ":xai-grok",
    # Contextual picker navigation commands handled before normal dispatch.
    ":back",
    ":cancel",
]

COMMANDS.extend(command for command in TUI_COMMAND_ALIASES if command not in COMMANDS)
