"""Official ACP agent list mirrored from the ACP documentation.

Source: https://agentclientprotocol.com/get-started/agents

This list is intentionally separate from installable registry metadata. The
ACP docs page is the broad compatibility list; local TOML files and the ACP
Registry provide richer run/install commands when we know them.
"""

from __future__ import annotations

from typing import TypedDict


class OfficialACPAgent(TypedDict):
    identity: str
    name: str
    short_name: str
    url: str
    author_name: str
    author_url: str
    description: str


OFFICIAL_ACP_AGENTS: tuple[OfficialACPAgent, ...] = (
    {
        "identity": "agentpool.phil65.github.io",
        "name": "AgentPool",
        "short_name": "agentpool",
        "url": "https://phil65.github.io",
        "author_name": "AgentPool",
        "author_url": "https://phil65.github.io",
        "description": "ACP-compatible agent listed by the Agent Client Protocol documentation.",
    },
    {
        "identity": "augmentcode.com",
        "name": "Augment Code",
        "short_name": "auggie",
        "url": "https://docs.augmentcode.com",
        "author_name": "Augment Code",
        "author_url": "https://www.augmentcode.com/",
        "description": "Augment Code's ACP-compatible software agent.",
    },
    {
        "identity": "autodev.github.io",
        "name": "AutoDev",
        "short_name": "autodev",
        "url": "https://github.com",
        "author_name": "AutoDev",
        "author_url": "https://github.com",
        "description": "ACP-compatible agent listed by the Agent Client Protocol documentation.",
    },
    {
        "identity": "blackbox.ai",
        "name": "Blackbox AI",
        "short_name": "blackbox",
        "url": "https://docs.blackbox.ai",
        "author_name": "Blackbox AI",
        "author_url": "https://www.blackbox.ai",
        "description": "Blackbox AI ACP-compatible coding agent.",
    },
    {
        "identity": "bub.dev",
        "name": "Bub",
        "short_name": "bub",
        "url": "https://github.com",
        "author_name": "Bub",
        "author_url": "https://github.com",
        "description": "Bub via the bub-acp-server adapter.",
    },
    {
        "identity": "claude.com",
        "name": "Claude Agent",
        "short_name": "claude",
        "url": "https://platform.claude.com",
        "author_name": "Anthropic",
        "author_url": "https://www.anthropic.com/",
        "description": "Anthropic Claude exposed through an ACP adapter.",
    },
    {
        "identity": "cline.bot",
        "name": "Cline",
        "short_name": "cline",
        "url": "https://cline.bot",
        "author_name": "Cline",
        "author_url": "https://cline.bot",
        "description": "Autonomous coding agent with ACP compatibility.",
    },
    {
        "identity": "codex.openai.com",
        "name": "Codex CLI",
        "short_name": "codex",
        "url": "https://developers.openai.com",
        "author_name": "OpenAI",
        "author_url": "https://openai.com",
        "description": "OpenAI Codex CLI via ACP adapter.",
    },
    {
        "identity": "codeassistant.dev",
        "name": "Code Assistant",
        "short_name": "codeassistant",
        "url": "https://github.com",
        "author_name": "Code Assistant",
        "author_url": "https://github.com",
        "description": "ACP-compatible coding assistant listed by the ACP documentation.",
    },
    {
        "identity": "crow-ai.dev",
        "name": "crow-cli",
        "short_name": "crow",
        "url": "https://crow-ai.dev",
        "author_name": "crow-cli",
        "author_url": "https://crow-ai.dev",
        "description": "Minimal ACP-native coding agent.",
    },
    {
        "identity": "cursor.com",
        "name": "Cursor",
        "short_name": "cursor",
        "url": "https://cursor.com",
        "author_name": "Cursor",
        "author_url": "https://cursor.com",
        "description": "Cursor's ACP-compatible coding agent.",
    },
    {
        "identity": "cagent.dev",
        "name": "Docker's cagent",
        "short_name": "cagent",
        "url": "https://github.com",
        "author_name": "Docker",
        "author_url": "https://www.docker.com/",
        "description": "Docker's ACP-compatible cagent runtime.",
    },
    {
        "identity": "fastagent.ai",
        "name": "fast-agent",
        "short_name": "fast-agent",
        "url": "https://fast-agent.ai",
        "author_name": "fast-agent",
        "author_url": "https://fast-agent.ai",
        "description": "ACP-compatible agent workflow runtime.",
    },
    {
        "identity": "factory.ai",
        "name": "Factory Droid",
        "short_name": "factory",
        "url": "https://factory.ai",
        "author_name": "Factory",
        "author_url": "https://factory.ai",
        "description": "Factory Droid ACP-compatible coding agent.",
    },
    {
        "identity": "fount.dev",
        "name": "fount",
        "short_name": "fount",
        "url": "https://github.com",
        "author_name": "fount",
        "author_url": "https://github.com",
        "description": "ACP-compatible agent listed by the Agent Client Protocol documentation.",
    },
    {
        "identity": "geminicli.com",
        "name": "Gemini CLI",
        "short_name": "gemini",
        "url": "https://github.com",
        "author_name": "Google",
        "author_url": "https://www.google.com",
        "description": "Google Gemini CLI ACP route; consumer users should migrate to Antigravity CLI.",
    },
    {
        "identity": "copilot.github.com",
        "name": "GitHub Copilot",
        "short_name": "copilot",
        "url": "https://github.com",
        "author_name": "GitHub",
        "author_url": "https://github.com",
        "description": "GitHub Copilot ACP support in public preview.",
    },
    {
        "identity": "goose.block.xyz",
        "name": "Goose",
        "short_name": "goose",
        "url": "https://block.github.io",
        "author_name": "Block",
        "author_url": "https://block.xyz",
        "description": "Local extensible ACP-compatible engineering agent.",
    },
    {
        "identity": "hermes-agent.nousresearch.com",
        "name": "Hermes Agent",
        "short_name": "hermes",
        "url": "https://hermes-agent.nousresearch.com",
        "author_name": "Nous Research",
        "author_url": "https://nousresearch.com",
        "description": "Hermes ACP-compatible agent.",
    },
    {
        "identity": "junie.jetbrains.com",
        "name": "Junie by JetBrains",
        "short_name": "junie",
        "url": "https://junie.jetbrains.com",
        "author_name": "JetBrains",
        "author_url": "https://www.jetbrains.com/",
        "description": "JetBrains' ACP-compatible AI coding agent.",
    },
    {
        "identity": "kimi.moonshot.cn",
        "name": "Kimi CLI",
        "short_name": "kimi",
        "url": "https://github.com",
        "author_name": "Moonshot AI",
        "author_url": "https://www.moonshot.cn",
        "description": "Moonshot AI Kimi CLI with ACP support.",
    },
    {
        "identity": "kiro.dev",
        "name": "Kiro CLI",
        "short_name": "kiro",
        "url": "https://kiro.dev",
        "author_name": "Kiro",
        "author_url": "https://kiro.dev",
        "description": "Kiro CLI ACP-compatible coding agent.",
    },
    {
        "identity": "minioncode.dev",
        "name": "Minion Code",
        "short_name": "minion",
        "url": "https://github.com",
        "author_name": "Minion Code",
        "author_url": "https://github.com",
        "description": "Enhanced ACP-compatible code assistant.",
    },
    {
        "identity": "mistral-vibe.mistral.ai",
        "name": "Mistral Vibe",
        "short_name": "mistral-vibe",
        "url": "https://github.com",
        "author_name": "Mistral AI",
        "author_url": "https://mistral.ai",
        "description": "Mistral's ACP-compatible coding assistant.",
    },
    {
        "identity": "openclaw.ai",
        "name": "OpenClaw",
        "short_name": "openclaw",
        "url": "https://docs.openclaw.ai",
        "author_name": "OpenClaw",
        "author_url": "https://openclaw.ai",
        "description": "OpenClaw ACP-compatible agent.",
    },
    {
        "identity": "opencode.ai",
        "name": "OpenCode",
        "short_name": "opencode",
        "url": "https://github.com",
        "author_name": "OpenCode",
        "author_url": "https://opencode.ai",
        "description": "Open-source coding agent with ACP support.",
    },
    {
        "identity": "openhands.dev",
        "name": "OpenHands",
        "short_name": "openhands",
        "url": "https://docs.openhands.dev",
        "author_name": "OpenHands",
        "author_url": "https://openhands.dev",
        "description": "OpenHands ACP-compatible agent.",
    },
    {
        "identity": "pi.dev",
        "name": "Pi",
        "short_name": "pi",
        "url": "https://github.com",
        "author_name": "Earendil Works",
        "author_url": "https://github.com",
        "description": "Pi coding agent via pi-acp adapter.",
    },
    {
        "identity": "poolside.ai",
        "name": "Poolside",
        "short_name": "poolside",
        "url": "https://github.com",
        "author_name": "Poolside",
        "author_url": "https://poolside.ai",
        "description": "Poolside ACP-compatible coding agent.",
    },
    {
        "identity": "qoder.com",
        "name": "Qoder CLI",
        "short_name": "qoder",
        "url": "https://docs.qoder.com",
        "author_name": "Qoder",
        "author_url": "https://qoder.com",
        "description": "Qoder CLI with ACP-compatible agentic coding capabilities.",
    },
    {
        "identity": "qwenlm.github.io",
        "name": "Qwen Code",
        "short_name": "qwen",
        "url": "https://github.com",
        "author_name": "Qwen",
        "author_url": "https://github.com",
        "description": "Alibaba Qwen coding assistant with ACP support.",
    },
    {
        "identity": "sigit.dev",
        "name": "siGit Code",
        "short_name": "sigit",
        "url": "https://github.com",
        "author_name": "siGit",
        "author_url": "https://github.com",
        "description": "Local-first ACP-compatible coding agent.",
    },
    {
        "identity": "stakpak.dev",
        "name": "Stakpak",
        "short_name": "stakpak",
        "url": "https://github.com",
        "author_name": "Stakpak",
        "author_url": "https://github.com",
        "description": "ACP-compatible DevOps and code assistance agent.",
    },
    {
        "identity": "stdiobus.dev",
        "name": "stdio Bus",
        "short_name": "stdio-bus",
        "url": "https://github.com",
        "author_name": "stdio Bus",
        "author_url": "https://github.com",
        "description": "ACP-compatible stdio bus agent.",
    },
    {
        "identity": "vtcode.dev",
        "name": "VT Code",
        "short_name": "vtcode",
        "url": "https://github.com",
        "author_name": "VT",
        "author_url": "https://github.com",
        "description": "Open-source ACP-compatible coding agent with shell safety.",
    },
)
